# See https://www.loraserver.io/lora-geo-server/install/config/ for a full
# configuration example and documentation.

[geo_server.backend]
name="collos"

[geo_server.backend.collos]

# Request timeout.
request_timeout=60
