version: "3"

services:
  loraserver:
    image: loraserver/loraserver:2
    volumes:
      - ./configuration/loraserver:/etc/loraserver

  appserver:
    image: theo024/lora-app-server:latest
    ports:
      - "8080:8080"
    volumes:
      - ./configuration/lora-app-server:/etc/lora-app-server

  gatewaybridge:
    image: loraserver/lora-gateway-bridge:2
    ports:
      - "1700:1700/udp"
    volumes:
      - ./configuration/lora-gateway-bridge:/etc/lora-gateway-bridge

  geoserver:
    image: loraserver/lora-geo-server:2
    volumes:
      - ./configuration/lora-geo-server:/etc/lora-geo-server

  geo-api:
    image: theo024/geo-api:latest
    ports:
      - "8081:8081"

  postgresql:
    image: postgres:9.6-alpine
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: theo024/mosquitto-auth-plug:latest
    ports:
      - "1883:1883"
    volumes:
      - ./configuration/mosquitto:/mosquitto/config

volumes:
  postgresqldata:
  redisdata:
